apiVersion: v1
kind: ConfigMap
metadata:
  name: trafficlight-configmap-0.0.1
  namespace: deviceshifu
data:
#    device name and image address
  driverProperties: |
    driverSku: Traffic Light
    driverImage: trafficlight-device:v0.0.1
#    available instructions
  instructions: |
    instructionSettings:
      defaultTimeoutSeconds: 8
    instructions:
      stop:
      caution:
      proceed:
      get_color:
      get_statue:
#    telemetry retrieval methods
#    in this examples, a device_health telemetry is collected by calling hello instruction every 1 second
  telemetries: |
    telemetries:
      device_health:
        properties:
          instruction: get_statue
          initialDelayMs: 1000
          intervalMs: 1000
