apiVersion: v1
kind: Service
metadata:
  labels:
    app: trafficlight
  name: trafficlight
  namespace: devices
spec:
  ports:
    - port: 11111
      protocol: TCP
      targetPort: 11111
  selector:
    app: trafficlight
  type: LoadBalancer

