{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "deviceshifu Num",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (kube_pod_info{namespace=\"deviceshifu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"shifu-crd-system|deviceshifu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "deviceshifu CPU rate",
   "type": "timeseries",
   "description": "CPU Info",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"deviceshifu\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"shifu-crd-system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage rate",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"deviceshifu|shifu-crd-system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem usage rate",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (node_namespace_pod_container:container_memory_working_set_bytes{namespace=~\"deviceshifu|shifu-crd-system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "deviceShifu Memory Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(namespace) (node_namespace_pod_container:container_memory_working_set_bytes{namespace=~\"deviceshifu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "deviceShifu Mem",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (node_namespace_pod_container:container_memory_working_set_bytes{namespace=\"deviceshifu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (node_namespace_pod_container:container_memory_working_set_bytes{namespace=\"deviceshifu\"})",
     "legendFormat": "-"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth%",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (irate(container_network_transmit_bytes_total{namespace=\"deviceshifu\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (irate(container_network_transmit_bytes_total{namespace=\"deviceshifu\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (irate(container_network_transmit_bytes_total{namespace=\"deviceshifu\"}[5m]))",
     "legendFormat": "-"
    }
   ]
  }
 ]
}