apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-opcua-deployment
  name: deviceshifu-opcua
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: deviceshifu-opcua-deployment
  type: LoadBalancer