apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-opcua
  namespace: devices
spec:
  sku: "opcua-test" 
  connection: Ethernet
  address: opc.tcp://192.168.0.111:4840/freeopcua/server #change this accordingly
  protocol: OPCUA
  protocolSettings:
    OPCUASetting:
      SecurityMode: None
      CertificateFileName: cert.pem
      PrivateKeyFileName: key.pem
      ConnectionTimeoutInMilliseconds: 5000
      AuthenticationMode: Certificate
      Username: user1
      Password: pwd1
