apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-socket
  namespace: devices
spec:
  sku: "testSocket" 
  connection: Ethernet
  address: 192.168.14.163:11122 #change this accordingly
  protocol: Socket
  protocolSettings:
    SocketSetting:
      encoding: hex
      networkType: tcp
      bufferLength: 10
