apiVersion: v1
kind: ConfigMap
metadata:
  name: http-configmap-0.0.1
  namespace: deviceshifu
data:
#    device name and image address
  driverProperties: |
    driverSku: HTTP Device
    driverImage: http-device:v0.0.1
#    available instructions
  instructions: |
    instructions:
      temperature:
        protocolPropertyList:
          DataFormat: PlainText
          ObjectId: /3303/0/5700
          EnableObserve: true
