apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-lwm2m
  name: deviceshifu-lwm2m
  namespace: deviceshifu
spec:
  ports:
    - name: deviceshifu
      port: 80
      protocol: TCP
      nodePort: 30080
      targetPort: 8080
    - name: lwm2mserver-coap
      port: 5683
      protocol: UDP
      nodePort: 30000
      targetPort: 5683
    - name: lwm2mserver-coaps
      port: 5684
      protocol: UDP
      nodePort: 30001
      targetPort: 5684
  selector:
    app: deviceshifu-lwm2m-deployment
  type: NodePort
