apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-mock-device
  namespace: devices
spec:
  selector:
    matchLabels:
      app: socket-mock-device
  template:
    metadata:
      labels:
        app: socket-mock-device
    spec:
      containers:
      - name: socket-mock-device
        image: socket-mock-device:v0.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 11122
