# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "github.com/edgenesis/shifu/pkg/k8s" # ignore update for shifu modules
      - dependency-name: "github.com/edgenesis/shifu/pkg/deviceshifu/mockdevice/mockdevice" # ignore update for shifu modules
