# golangci-lint v2 configuration
version: "2"

linters:
  exclusions:
    rules:
      # Examples are not production code - skip strict error checking
      - path: ^examples/
        linters:
          - errcheck
