apiVersion: v1
kind: ServiceAccount
metadata:
  name: edgedevice-helloworld-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgedevice-helloworld-clusterrole
rules:
- apiGroups:
  - shifu.edgenesis.io
  resources:
  - edgedevices
  verbs: ["get", "update"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edgedevice-helloworld-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edgedevice-helloworld-clusterrole
subjects:
- kind: ServiceAccount
  name: edgedevice-helloworld-sa
  namespace: default