apiVersion: v1
kind: Service
metadata:
  labels:
    app: edgedevice-helloworld-deployment
  name: edgedevice-helloworld-service
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: edgedevice-helloworld-deployment
  type: LoadBalancer
