apiVersion: v1
kind: ConfigMap
metadata:
  name: helloworld-configmap-0.0.1
  namespace: deviceshifu
data:
#    device name and image address
  driverProperties: |
    driverSku: Hello World
    driverImage: helloworld-device:v0.0.1
#    available instructions
  instructions: |
    instructionSettings:
      defaultTimeoutSeconds: 8
    instructions:
      hello:
#    telemetry retrieval methods
#    in this example, a device_health telemetry is collected by calling hello instruction every 1 second
  telemetries: |
    telemetrySettings:
      telemetryUpdateIntervalInMilliseconds: 6000
      telemetryTimeoutInMilliseconds: 3000
      telemetryInitialDelayInMilliseconds: 7000
    telemetries:
      device_health:
        properties:
          instruction: hello
          initialDelayMs: 1000
          intervalMs: 1000
