apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: alpine
    volumeMounts:
    - name: foo
      mountPath: "/etc/edgedevice/config"
      readOnly: true
  volumes:
  - name: foo
    configMap:
      name: mockdevice-configmap-0.0.1
