apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edgedevice-mockdevice-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edgedevice-mockdevice-clusterrole
subjects:
- kind: ServiceAccount
  name: edgedevice-mockdevice-sa
  namespace: deviceshifu
