apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-mockdevice-deployment
  name: deviceshifu-mockdevice
spec:
  ports:
  - port: 1234
    protocol: TCP
    targetPort: 8080
  selector:
    app: deviceshifu-mockdevice-deployment
  type: LoadBalancer
