apiVersion: v1
kind: ConfigMap
metadata:
  name: humidity-detector-configmap-0.0.1
  namespace: deviceshifu
data:
#    device name and image address
  driverProperties: |
    driverSku: HumidityDetector
    driverImage: edgehub/humidity-detector:nightly

  customInstructionsPython: |
    humidity_custom: humidity_raw_data
#    available instructions
  instructions: |
    instructionSettings:
      defaultTimeoutSeconds: 8
    instructions:
      humidity:
      humidity_custom:
#    telemetry retrieval methods
  telemetries: |
    telemetrySettings:
      telemetryUpdateIntervalInMilliseconds: 6000
      telemetryTimeoutInMilliseconds: 3000
      telemetryInitialDelayInMilliseconds: 7000
    telemetries:
      humidity-detector-custom:
        properties:
          instruction: humidity_custom
          initialDelayMs: 1000
          intervalMs: 3000
          pushSettings:
            telemetryCollectionService: push-custom-data
      humidity-detector:
        properties:
          instruction: humidity
          initialDelayMs: 1000
          intervalMs: 3000
          pushSettings:
            telemetryCollectionService: push-data
