apiVersion: v1
kind: ConfigMap
metadata:
  name: humidity-detector-configmap-0.0.1
  namespace: deviceshifu
data:
#    device name and image address
  driverProperties: |
    driverSku: HumidityDector
    driverImage: humidity-detector:v0.0.1

  customInstructionsPython: |
    humidity:
#    available instructions
  instructions: |
    instructionSettings:
      defaultTimeoutSeconds: 8
    instructions:
      humidity:
#    telemetry retrieval methods
  telemetries: |
    telemetrySettings:
      telemetryUpdateIntervalInMilliseconds: 6000
      telemetryTimeoutInMilliseconds: 3000
      telemetryInitialDelayInMilliseconds: 7000
    telemetries:
      device_health:
        properties:
          instruction: humidity
          initialDelayMs: 1000
          intervalMs: 1000
