apiVersion: v1
kind: Service
metadata:
  labels:
    app: humidity-detector
  name: humidity-detector
  namespace: devices
spec:
  ports:
    - port: 11111
      protocol: TCP
      targetPort: 11111
  selector:
    app: humidity-detector
  type: LoadBalancer

