apiVersion: v1
kind: Service
metadata:
  labels:
    app: mockserver
  name: mockserver
  namespace: devices
spec:
  ports:
    - port: 11111
      protocol: TCP
      targetPort: 11111
  selector:
    app: mockserver
  type: LoadBalancer
