apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mockserver
  name: mockserver
  namespace: devices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockserver
  template:
    metadata:
      labels:
        app: mockserver
    spec:
      containers:
        - image: edgehub/mockserver:v0.50.0-rc1
          imagePullPolicy: Never
          name: mockserver
          ports:
            - containerPort: 11111
