apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-tcp-deployment
  name: deviceshifu-tcp
  namespace: deviceshifu
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: deviceshifu-tcp-deployment
  type: LoadBalancer
