apiVersion: v1
kind: Service
metadata:
  name: telemetryservice
  namespace: shifu-service
spec:
  selector:
    app: telemetryservice
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
