apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-tecan
  namespace: devices
spec:
  sku: "Tecan SPark" 
  connection: Ethernet
  address: tecan.devices.svc.cluster.local:11111
  protocol: HTTP
status:
  edgedevicephase: "Pending"
