apiVersion: v1
kind: Service
metadata:
  labels:
    app: edgedevice-tecan-deployment
  name: edgedevice-tecan
spec:
  ports:
  - port: 1234
    protocol: TCP
    targetPort: 8080
  selector:
    app: edgedevice-tecan-deployment
  type: LoadBalancer
