apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tecan
  name: tecan
  namespace: devices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tecan
  strategy: {}
  template:
    metadata:
      labels:
        app: tecan
    spec:
      containers:
      - image: edgehub/mockdevice_tecan:v0.0.1
        name: tecan
        ports:
        - containerPort: 11111
        env:
        - name: MOCKDEVICE_NAME
          value: tecan
        - name: MOCKDEVICE_PORT
          value: "11111"
