apiVersion: v1
kind: Service
metadata:
  labels:
    app: tecan
  name: tecan
  namespace: devices
spec:
  ports:
  - port: 11111
    protocol: TCP
    targetPort: 11111
  selector:
    app: tecan
  type: LoadBalancer
