FROM golang:1.18-alpine

WORKDIR /worker

COPY examples/deviceshifu/demo_device/edgedevice-socket/server.go server.go

RUN go build -o /output/server server.go

EXPOSE 11122:11122/tcp

ENTRYPOINT [ "/output/server" ]