apiVersion: v1
kind: ConfigMap
metadata:
  name: socket-configmap-0.0.1
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: testSocket
    driverImage: 
  instructions: |
    instructions:
      cmd:
        readWrite: RW
        safe: false
        description: |
          Send a raw command over the socket connection and receive a response.
  telemetries: |
    telemetrySettings:
      telemetryUpdateIntervalInMiliseconds: 1000
