apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-socket
  namespace: devices
spec:
  sku: "testSocket" 
  connection: Ethernet
  address: mockdevice-socket.devices.svc.cluster.local:11122 #change this accordingly
  protocol: Socket
  protocolSettings:
    SocketSetting:
      encoding: utf-8
      networkType: tcp