apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-socket
  namespace: devices
spec:
  sku: "testSocket"
  connection: Ethernet
  address: mockdevice-socket.devices.svc.cluster.local:11122 #change this accordingly
  protocol: Socket
  description: |
    Socket-based test device. Communicates over raw TCP socket
    with UTF-8 encoding.
  connectionInfo: |
    Raw socket protocol. UTF-8 encoding.
  protocolSettings:
    SocketSetting:
      encoding: utf-8
      networkType: tcp
      bufferLength: 10