apiVersion: v1
kind: ConfigMap
metadata:
  name: socket-configmap-0.0.1
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: testSocket
    driverImage: 
  instructions: |
    instructions:
      cmd:
  telemetries: |
    telemetrySettings:
      telemetryUpdateIntervalInMiliseconds: 1000
