apiVersion: v1
kind: ConfigMap
metadata:
  name: helloworld-configmap-0.0.1
  namespace: default
data:
#    device name and image address
  driverProperties: |
    driverSku: Hello World
    driverImage: helloworld-device:v0.0.1
#    available instructions
  instructions: |
    hello:
    idle:
#    telemetry retrieval methods
#    in this example, a device_health telemetry is collected by calling hello instruction every 1 second
  telemetries: |
    device_health:
      properties:
        instruction: hello
        initialDelayMs: 1000
        intervalMs: 1000
  states: |
    stateMachineEnabled: true
    initialState: idle
    initialInstruction: idle
    globalDefaultStateDuration: 10
    globalDefaultTransition: idle
    globalDefaultTransitionInstruction: idle
    availableStates:
    - state: idle
      availableInstructions:
      - availableInstruction: hello
        nextState: helloing
        ackReturn: HTTP 200
        doneSignal: HTTP 200
        exceptionReturn: HTTP 500
      - availableInstruction: idle
        nextState: idle
    - state: helloing
      defaultStateDuration: 5
      defaultTransition: idle
      defaultTransitionInstruction: idle
      availableInstructions:
      - availableInstruction: idle
        nextState: idle

