apiVersion: v1
kind: ConfigMap
metadata:
  name: thermometer-configmap-0.0.1
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: Thermometer
    driverImage: edgenesis/thermometer:v0.0.1
  instructions: |
    get_status:
    read_value:
  telemetries: |
    device_health:
      properties:
        instruction: get_status
        initialDelayMs: 1000
        intervalMs: 1000
