apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-thermometer
  namespace: devices
spec:
  sku: "Thermometer" 
  connection: Ethernet
  address: thermometer.devices.svc.cluster.local:11111
  protocol: HTTP
status:
  edgedevicephase: "Pending"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thermometer-configmap-0.0.1
  namespace: default
data:
  driverProperties: |
    driverSku: Thermometer
    driverImage: edgenesis/thermometer:v0.0.1
  instructions: |
    get_status:
    read_value:
  telemetries: |
    device_health:
      properties:
        instruction: get_status
        initialDelayMs: 1000
        intervalMs: 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: edgedevice-thermometer-deployment
  name: edgedevice-thermometer-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgedevice-thermometer-deployment
  template:
    metadata:
      labels:
        app: edgedevice-thermometer-deployment
    spec:
      containers:
      - image: edgehub/deviceshifu-http:v0.0.1
        name: deviceshifu-http
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: edgedevice-config
          mountPath: "/etc/edgedevice/config"
          readOnly: true
        env:
        - name: EDGEDEVICE_NAME
          value: "edgedevice-thermometer"
        - name: EDGEDEVICE_NAMESPACE
          value: "devices"
      volumes:
      - name: edgedevice-config
        configMap:
          name: thermometer-configmap-0.0.1
      serviceAccountName: edgedevice-readwrite-sa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: edgedevice-thermometer-deployment
  name: edgedevice-thermometer
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: edgedevice-thermometer-deployment
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thermometer
  name: thermometer
  namespace: devices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thermometer
  strategy: {}
  template:
    metadata:
      labels:
        app: thermometer
    spec:
      containers:
      - image: edgehub/mockdevice_thermometer:v0.0.1
        name: thermometer
        ports:
        - containerPort: 11111
        env:
        - name: MOCKDEVICE_NAME
          value: thermometer
        - name: MOCKDEVICE_PORT
          value: "11111"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thermometer
  name: thermometer
  namespace: devices
spec:
  ports:
  - port: 11111
    protocol: TCP
    targetPort: 11111
  selector:
    app: thermometer
  type: LoadBalancer
