apiVersion: v1
kind: Service
metadata:
  labels:
    app: plc
  name: plc
  namespace: devices
spec:
  ports:
  - port: 11111
    protocol: TCP
    targetPort: 11111
  selector:
    app: plc
  type: LoadBalancer
