# permissions for end users to edit telemetryservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telemetryservice-editor-role
rules:
- apiGroups:
  - shifu.edgenesis.io
  resources:
  - telemetryservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shifu.edgenesis.io
  resources:
  - telemetryservices/status
  verbs:
  - get
