data:
  driverProperties: |
    driverSku: Edgenesis Mock Device
    driverImage: edgenesis/mockdevice:v0.0.1
    driverExecution: python mock_driver.py
  instructions: |
    instructionSetting:
      defaultTimeoutSeconds:4
    instructions:
      get_reading:
      get_status:
      set_reading:
        argumentPropertyList:
        - valueType: "Int32"
          readWrite: "W"
          defaultValue: null
      start:
      stop:
  telemetries: |
    telemetrySettings:
      telemetryUpdateIntervalInMilliseconds: 6000
      telemetryTimeoutInMilliseconds: 3000
      defaultPushToServer: true
      defaultTelemetryCollectionService: push-endpoint-1
    telemetries:
      device_health:
        properties:
          instruction: get_status
          initialDelayMs: 1000
          intervalMs: 1000
          pushSettings:
            telemetryCollectionService: push-endpoint-2
      get_reading:
        properties:
          instruction: get_reading
          initialDelayMs: 1000
          intervalMs: 1000
      device_health2:
        properties:
          instruction: get_reading
          initialDelayMs: 1000
          intervalMs: 1000
          pushSettings:
            pushToServer: false
