apiVersion: v1
kind: ConfigMap
metadata:
  name: led-configmap-0.0.1
  namespace: default
data:
  driverProperties: |
    driverSku: rpi
    driverImage: edgenesis/rpi:v0.0.1
  instructions: |
    led_control:
    led_status:
    led_red_on:
    led_yellow_on:
    led_green_on:
# Telemetries are configurable health checks of the EdgeDevice
# Developer/user can configure certain instructions to be used as health check
# of the device. In this example, the device_health telemetry is mapped to
# "get_status" instruction, executed every 1000 ms
  telemetries: |
    device_health:
      properties:
        instruction: led_status
        initialDelayMs: 1000
        intervalMs: 1000

  states: |
    initialState: red
    initialInstruction: led_red_on
    globalDefaultStateDuration: 10
    globalDefaultTransition: red
    globalDefaultTransitionInstruction: led_red_on
    globalApplicationEndpoint: unityserver:8092
    availableStates:
    - state: red
      defaultTransition: green
      defaultTransitionInstruction: led_green_on
      availableInstructions:
      - availableInstruction: led_green_on
        nextState: green
    - state: green
      defaultStateDuration: 6
      defaultTransition: yellow
      defaultTransitionInstruction: led_yellow_on
      availableInstructions:
      - availableInstruction: led_red_on
        nextState: red
      - availableInstruction: led_yellow_on
        nextState: yellow
    - state: yellow
      defaultStateDuration: 3
      availableInstructions:
      - availableInstruction: led_red_on
        nextState: red
      - availableInstruction: led_green_on
        nextState: green
