data:
  driverProperties: |
    driverSku: Edgenesis Mock Device
    driverImage: edgenesis/mockdevice:v0.0.1
    driverExecution: python mock_driver.py
  instructions: |
    instructions:
      get_topicmsg1:
        protocolPropertyList:
          MQTTTopic: "/test/test1"
      get_topicmsg2:
        protocolPropertyList:
          MQTTTopic: "/test/test2"
      set_reading:
        argumentPropertyList:
        - valueType: "Int32"
          readWrite: "W"
          defaultValue: null
      get_topicmsg3:
        protocolPropertyList:
          MQTTTopic: "/test/test3"
      get_topicmsg4:
        protocolPropertyList:
          MQTTTopic: "/test/test4"
  telemetries: |
    telemetrySettings:
      telemetryUpdateIntervalInMilliseconds: 1000
