data:
  driverProperties: |
    driverSku: Edgenesis Mock Device
    driverImage: edgenesis/mockdevice:v0.0.1
  instructions: |
    instructions:
      cmd:
  telemetries: |
    telemetrySettings:
      telemetryUpdateIntervalInMilliseconds: 1000
