# Sample configmap snippet. You need to modify this accordingly.
data:
  driverProperties: |
    driverSku: Edgenesis Mock Device
    driverImage: edgenesis/mockdevice:v0.0.1
    driverExecution: python mock_driver.py
  instructions: |
    instructions:
      get_value:
      get_time:
      get_server:
  telemetries: |
    telemetrySettings:
      telemetryUpdateIntervalInMilliseconds: 1000
    telemetries:
      device_health:
        properties:
          instruction: get_server
          initialDelayMs: 1000
          intervalMs: 1000
