# Build the manager binary
FROM --platform=$BUILDPLATFORM golang:1.18.4 as builder

WORKDIR /shifu

ENV GOPROXY=https://goproxy.cn,direct
ENV GO111MODULE=on
ENV GOPRIVATE=github.com/Edgenesis

COPY pkg/deviceshifu/mockdevice deviceshifu/pkg/mockdevice

WORKDIR /shifu/deviceshifu/pkg/mockdevice/mockdevice

COPY go.mod go.mod
COPY go.sum go.sum
COPY pkg/deviceshifu pkg/deviceshifu
RUN go mod download

# Build the Go app
ARG TARGETOS
ARG TARGETARCH

RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -a \
    -o /output/mockdevice-thermometer \
    /shifu/deviceshifu/pkg/mockdevice/mockdevice-thermometer/mockdevice-thermometer.go

FROM edgehub/distroless-static:nonroot
WORKDIR /
COPY --from=builder /output/mockdevice-thermometer mockdevice-thermometer

# Command to run the executable
USER 65532:65532
ENTRYPOINT ["/mockdevice-thermometer"]
