apiVersion: v1
kind: ConfigMap
metadata:
  name: http-configmap-0.0.1
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: Test HTTP Server
    driverImage:
  instructions: |
    instructions:
      get_status:
      gatewayPropertyList:
        ObjectId: /3303/0/5700
        DataType: float
  telemetries: |
    telemetries:
      device_health:
        properties:
          instruction: get_status
          initialDelayMs: 1000
          intervalMs: 1000
