data:
  driverProperties: |
    driverSku: Edgenesis Mock Device
    driverImage: edgenesis/mockdevice:v0.0.1
    driverExecution: python mock_driver.py
  instructions: |
    set_reading:
      argumentPropertyList:
      - valueType: "Int32"
        readWrite: "W"
        defaultValue: null
    start:
    stop:
  telemetries: |
    telemetrySettings:
      telemetryUpdateIntervalInMiliseconds: 1000
