apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-robot
spec:
  sku: "Franka Emika" 
  connection: Ethernet
  address: 10.0.0.3:80
  protocol: HTTP
status:
  edgedevicephase: "Pending"
