apiVersion: v1
kind: ConfigMap
metadata:
  name: deviceshifu-lwm2m
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: LwM2M Device
    driverImage: lwm2m-device:v0.0.1
  instructions: |
    instructions:
      read_value:
        protocolPropertyList:
          ObjectId: /3442/0/130
          EnableObserve: false
