# permissions for end users to edit edgedevices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgedevice-editor-role
rules:
- apiGroups:
  - iot.edgenesis.io.edgenesis.io
  resources:
  - edgedevices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iot.edgenesis.io.edgenesis.io
  resources:
  - edgedevices/status
  verbs:
  - get
