# permissions for end users to view telemetryservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telemetryservice-viewer-role
rules:
- apiGroups:
  - shifu.edgenesis.io
  resources:
  - telemetryservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - shifu.edgenesis.io
  resources:
  - telemetryservices/status
  verbs:
  - get
