apiVersion: v1
kind: ConfigMap
metadata:
  name: plc4x-configmap
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: testPlc4x
    driverImage: 
  instructions: |
    instructions:
  telemetries: |
    telemetrySettings:
