apiVersion: v1
kind: Service
metadata:
  labels:
    app: robotarm
  name: robotarm
  namespace: devices
spec:
  ports:
  - port: 11111
    protocol: TCP
    targetPort: 11111
  selector:
    app: robotarm
  type: LoadBalancer
