apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rtsp-record-deployment
  name: rtsp-record-deployment
  namespace: shifu-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtsp-record-deployment
  template:
    metadata:
      labels:
        app: rtsp-record-deployment
    spec:
      containers:
        - image: edgehub/rtsp-record:nightly
          name: deviceshifu-rtsp-record
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_LISTEN_PORT
              value: :8080
            - name: EDGEDEVICE_NAMESPACE
              value: shifu-app
          volumeMounts:
            - name: storage-pv
              mountPath: /data
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      volumes:
        - name: storage-pv
          persistentVolumeClaim:
            claimName: rtsp-pvc
      serviceAccountName: rtsp-record-sa
