apiVersion: v1
kind: PersistentVolume
metadata:
  name: rtsp-pv
  namespace: shifu-app
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/rtsp"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rtsp-pvc
  namespace: shifu-app
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
