apiVersion: v1
kind: Service
metadata:
  labels:
    app: rtsp-record-deployment
  name: rtsp-record
  namespace: shifu-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rtsp-record-deployment
  type: NodePort
