apiVersion: v1
kind: ConfigMap
metadata:
  name: thermometer-configmap-0.0.1
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: Thermometer
    driverImage: edgenesis/thermometer:v0.0.1
  instructions: |
    instructionSettings:
      defaultTimeoutSeconds: 8
    instructions:
      get_status:
        readWrite: R
        safe: true
        description: |
          GET /get_status
          Returns device health and uptime info.
      read_value:
        readWrite: R
        safe: true
        description: |
          GET /read_value
          Returns the current temperature reading in Celsius.
  telemetries: |
    telemetries:
      device_health:
        properties:
          instruction: get_status
          initialDelayMs: 1000
          intervalMs: 1000
