apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-thermometer
  namespace: devices
spec:
  sku: "Thermometer" 
  connection: Ethernet
  address: thermometer.devices.svc.cluster.local:11111
  protocol: HTTP
