apiVersion: v1
kind: ConfigMap
metadata:
  name: http-configmap-0.0.1
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: HTTP Device
    driverImage: http-device:v0.0.1
  instructions: |
    instructions:
      get_file_mp4:
  telemetries: |
    telemetrySettings:
      telemetryUpdateIntervalInMilliseconds: 10000
      telemetryTimeoutInMilliseconds: 2500
    telemetries:
      push_file:
        properties:
          instruction: get_file_mp4
          pushSettings:
            telemetryCollectionService: push-file-mp4
