apiVersion: v1
kind: ConfigMap
metadata:
  name: http-configmap-0.0.1
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: HTTP Device
    driverImage: http-device:v0.0.1
  instructions: |
    instructions:
      get_file:
  telemetries: |
    telemetrySettings:
      telemetryUpdateIntervalInMilliseconds: 10000
      telemetryTimeoutInMilliseconds: 20000
    telemetries:
      push_file:
        properties:
          instruction: get_file
          pushSettings:
            telemetryCollectionService: push-file-mp4
