apiVersion: v1
kind: ConfigMap
metadata:
  name: thermometer-configmap-0.0.1
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: Thermometer
    driverImage: edgenesis/thermometer:v0.0.1
  instructions: |
    instructionSettings:
      defaultTimeoutSeconds: 8
    instructions:
      read_value:
        gatewayPropertyList:
          ObjectId: /3442/0/130
          DataType: float
  telemetries: |
    telemetries:
      device_health:
        properties:
          instruction: get_status
          initialDelayMs: 1000
          intervalMs: 1000
