apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-thermometer-deployment
  name: deviceshifu-thermometer
  namespace: deviceshifu
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: deviceshifu-thermometer-deployment
  type: LoadBalancer
