apiVersion: apps/v1
kind: Deployment
metadata:
  name: deviceshifu-sensor-array
  namespace: deviceshifu
  labels:
    app: deviceshifu-sensor-array
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-sensor-array
  template:
    metadata:
      labels:
        app: deviceshifu-sensor-array
    spec:
      containers:
      - name: deviceshifu-http
        image: edgehub/deviceshifu-http-nats:nightly
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: deviceshifu-config
          mountPath: "/etc/edgedevice/config"
          readOnly: true
        env:
        - name: EDGEDEVICE_NAME
          value: "edgedevice-sensor-array"
        - name: EDGEDEVICE_NAMESPACE
          value: "devices"
      volumes:
      - name: deviceshifu-config
        configMap:
          name: deviceshifu-sensor-array-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: deviceshifu-sensor-array
  namespace: deviceshifu
  labels:
    app: deviceshifu-sensor-array
spec:
  selector:
    app: deviceshifu-sensor-array
  ports:
  - port: 8080
    targetPort: 8080
