--- #telemetry_service.yaml
apiVersion: shifu.edgenesis.io/v1alpha1
kind: TelemetryService
metadata:
  name: push-endpoint-1
  namespace: devices
spec:
  protocol: MQTT
  address: http://telemetryservicemqtt.shifuts.svc.cluster.local
  serviceSettings:
    MQTTSetting:
      MQTTTopic: /test/test
      MQTTServerAddress: mosquitto-service.devices.svc.cluster.local:1883

--- #telemetry_service2.yaml
apiVersion: shifu.edgenesis.io/v1alpha1
kind: TelemetryService
metadata:
  name: push-endpoint-2
  namespace: devices
spec:
  protocol: MQTT
  address: http://telemetryservicemqtt.shifuts.svc.cluster.local
  serviceSettings:
    MQTTSetting:
      MQTTTopic: /test/test
      MQTTServerAddress: mosquitto-service.devices.svc.cluster.local:1883