apiVersion: v1
kind: ConfigMap
metadata:
  name: http-configmap-0.0.1
  namespace: deviceshifu
data:
#    device name and image address
  driverProperties: |
    driverSku: HTTP Device
    driverImage: http-device:v0.0.1
#    available instructions
  instructions: |
    instructions:
      status:
      info:
#    telemetry retrieval methods
#    in this example, a device_health telemetry is collected by calling hello instruction every 1 second
  telemetries: |
    telemetrySettings:
      telemetryUpdateIntervalInMilliseconds: 6000
      telemetryTimeoutInMilliseconds: 3000
      defaultPushToServer: true
      defaultTelemetryCollectionService: push-endpoint-1
    telemetries:
      device_health:
        properties:
          instruction: status
          pushSettings:
            telemetryCollectionService: push-endpoint-2
      device_health2:
        properties:
          instruction: info
          pushSettings:
            pushToServer: false
