apiVersion: v1
kind: Namespace
metadata:
  name: devices
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edgedevice-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgedevice-clusterrole
rules:
- apiGroups:
  - shifu.edgenesis.io
  resources:
  - edgedevices
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edgedevice-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edgedevice-clusterrole
subjects:
- kind: ServiceAccount
  name: edgedevice-sa
  namespace: default