--- #telemetry_service.yaml
apiVersion: shifu.edgenesis.io/v1alpha1
kind: TelemetryService
metadata:
  name: push-endpoint-1
  namespace: devices
spec:
  address: http://telemetryservice.shifu-service.svc.cluster.local
  serviceSettings:
  - SQLSetting:
    serverAddress: 192.168.14.163:6041
    username: root
    secret: taosdata
    dbName: shifu
    dbTable: testTable2
    dbtype: TDEngine
  - SQLSetting:
    serverAddress: 192.168.14.163:6041
    username: root
    secret: taosdata
    dbName: shifu
    dbTable: testTable2
    dbtype: TDEngine
  - MQTTSetting:
    serverAddress: 192.168.14.163:6041
    username: root
    secret: taosdata
    dbName: shifu
    dbTable: testTable2
    dbtype: TDEngine
  - HTTPSetting:
