apiVersion: v1
kind: Service
metadata:
  labels:
    app: edgedevice-mqtt-deployment
  name: edgedevice-mqtt
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: edgedevice-mqtt-deployment
  type: LoadBalancer
