apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-configmap-0.0.1
  namespace: default
data:
  driverProperties: |
    driverSku: testMQTT
    driverImage: 
  instructions: |
    
  telemetries: |
    device_health:
      properties:

