apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-configmap-0.0.1
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: testMQTT
    driverImage: 
  instructions: |
    instructions:
      get_topicmsg1:
        protocolPropertyList:
          MQTTTopic: "/test/test1"
      get_topicmsg2:
        protocolPropertyList:
          MQTTTopic: "/test/test2"
      get_topicmsg3:
        protocolPropertyList:
          MQTTTopic: "/test/test3"
      get_topicmsg4:
        protocolPropertyList:
          MQTTTopic: "/test/test4"
  telemetries: |
    telemetries:
      device_health:
        properties:
  controlMsgs: |
      moving_the_device: "device_finish_moving"
