apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-configmap-0.0.1
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: testMQTT
    driverImage: 
  instructions: |
    connectionInfo: |
      MQTT broker: mqtt://deviceshifu-mqtt.deviceshifu.svc.cluster.local
      Topics: /test/test1 through /test/test4
    instructions:
      get_topicmsg1:
        readWrite: R
        hasSideEffects: false
        description: |
          Subscribe to /test/test1 topic for messages.
        protocolPropertyList:
          MQTTTopic: "/test/test1"
      get_topicmsg2:
        readWrite: R
        hasSideEffects: false
        description: |
          Subscribe to /test/test2 topic for messages.
        protocolPropertyList:
          MQTTTopic: "/test/test2"
      get_topicmsg3:
        readWrite: R
        hasSideEffects: false
        description: |
          Subscribe to /test/test3 topic for messages.
        protocolPropertyList:
          MQTTTopic: "/test/test3"
      get_topicmsg4:
        readWrite: R
        hasSideEffects: false
        description: |
          Subscribe to /test/test4 topic for messages.
        protocolPropertyList:
          MQTTTopic: "/test/test4"
  telemetries: |
    telemetries:
      device_health:
        properties:
  controlMsgs: |
      moving_the_device: "device_finish_moving"
