apiVersion: v1
kind: ConfigMap
metadata:
  name: powershell-configmap-0.0.1
  namespace: default
data:
  driverProperties: |
    driverSku: testPowerShell
    driverImage: 
    driverExecution: "Powershell.exe"
  instructions: |
    issue_cmd:
    stub_health:
  telemetries: |
    device_health:
      properties:

