apiVersion: v1
kind: ConfigMap
metadata:
  name: deviceshifu-powershell-configmap-0.0.1
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: testPowerShell
    driverImage: 
    driverExecution: "Powershell.exe"
  instructions: |
    instructions:
      issue_cmd:
      stub_health:
  telemetries: |
    telemetrySettings:
      telemetryUpdateIntervalInMilliseconds: 6000
      telemetryTimeoutInMilliseconds: 3000
    telemetries:
      device_health:
        properties:
          instruction: stub_health
