apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-agv
  namespace: devices
spec:
  sku: "AGV" 
  connection: Ethernet
  address: agv.devices.svc.cluster.local:11111
  protocol: HTTP
  customMetadata:
    Vendor: Quicktron
    Type: AMR
    Model: M60
    LoadType: Lifting beneath rack
    HWrevision: v2
    Dimensions: 956*730*240 mm
    RatedLoad: Rated load
    BatteryCapacity: 48V/36Ah
    ChargingTime: 9h
    AmbientTemperature: 0-45C
