apiVersion: v1
kind: ConfigMap
metadata:
  name: plc-configmap-0.0.1
  namespace: deviceshifu
data:
#    device name and image address
  driverProperties: |
    driverSku: PLC
    driverImage: plc-device:v0.0.1
    driverExecution: " "
#    available instructions
  instructions: |
    instructions:
      sendsinglebit:
      sendcontent:
      getcontent:
      getcpuordercode:
#    telemetry retrieval methods
#    in this example, a device_health telemetry is collected by calling hello instruction every 1 second
  telemetries: |
    telemetries:
      device_health:
        properties:
          instruction: getcpuordercode
          initialDelayMs: 1000
          intervalMs: 1000
