FROM python:3.9-bullseye

WORKDIR /worker

COPY examples/deviceshifu/demo_device/edgedevice-opcua/requirements.txt requirements.txt
COPY examples/deviceshifu/demo_device/edgedevice-opcua/server.py server.py

RUN pip3 install -r requirements.txt

CMD [ "python3","/worker/server.py" ]