apiVersion: apps/v1
kind: Deployment
metadata:
  name: opcua-device
  namespace: devices
spec:
  selector:
    matchLabels:
      app: opcua-device
  template:
    metadata:
      labels:
        app: opcua-device
    spec:
      containers:
      - name: opcua-device
        image: edgehub/mockdevice-opcua:v0.6.0-rc1
        ports:
        - containerPort: 4840
        readinessProbe:
          tcpSocket:
            port: 4840
          initialDelaySeconds: 3
