apiVersion: v1
kind: ConfigMap
metadata:
  name: opcua-configmap-0.0.1
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: Test OPC UA Server
    driverImage: 
  instructions: |
    instructions:
      get_value:
        protocolPropertyList:
          OPCUANodeID: "ns=2;i=2"
      get_time:
        protocolPropertyList:
          OPCUANodeID: "i=2258"
      get_server:
        protocolPropertyList:
          OPCUANodeID: "i=2261"
  telemetries: |
    telemetrySettings:
      telemetryUpdateIntervalInMiliseconds: 1000
    telemetries:
      device_health:
        properties:
          instruction: get_server
          initialDelayMs: 1000
          intervalMs: 1000
