# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: |
         go mod tidy -v
         sudo apt-get install libpcap-dev docker docker-compose
      - name: Build executable files
        run: |
          make build
      - name: build images
        run: |
          make buildx-build-image-deviceshifu
          make buildx-push-image-deviceshifu
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build artifacts
          path: |

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false